repos:
  - repo: local
    hooks:
    - id: no-dash-e
      name: nodashe
      description: check no editable modules in requirements
      entry: '\-e '
      language: pygrep
      files: '.*requirements.txt'
      types: [file]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: trailing-whitespace
        types_or:
          - "python"
          - "yaml"
          - "json"
          - "markdown"
          - "html"
          - "javascript"
      - id: check-byte-order-marker
      - id: check-json
      - id: forbid-new-submodules
      - id: check-added-large-files
        args: ['--maxkb=2500']
      - id: check-merge-conflict


  # TODO this seems to be gathering stuff from outside the virtual env.
  # - repo: https://github.com/dhatim/python-license-check
  #   rev: 0.9.2
  #   hooks:
  #     - id: liccheck
  #       language: system
  #       args: ["--no-deps"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs

  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.6
    hooks:
      - id: fix-smartquotes
        types_or:
          - "python"
          - "yaml"
          - "json"
          - "markdown"
          - "html"
          - "javascript"
      - id: fix-ligatures
        types_or:
          - "python"
          - "yaml"
          - "json"
          - "markdown"
          - "html"
          - "javascript"
      - id: fix-spaces
        types_or:
          - "python"
          - "yaml"
          - "json"
          - "markdown"
          - "html"
          - "javascript"


  # - repo: https://github.com/ikamensh/flynt/
  #   rev: '1.0.1'
  #   hooks:
  #   -   id: flynt
  #       args:
  #       - "--transform-joins"
  #       - "--transform-concats"

  # Set to select only obvious errors
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.5
    hooks:
      # Run the linter.
      - id: ruff
        args:
        - "--fix"
        # Errors
        - "--select=PLE"
        # Syntax error
        - "--select=E999"
        # Mostly have auto fixes available
        - "--select=PIE"
        - "--select=UP"
        - "--select=NPY"
        # Autofixable quote rules
        - "--select=Q"
        - "--select=E722"
        # Fix bad escape sequence
        - "--select=W605"
      # Run the formatter.
      - id: ruff-format


  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: default\.nix|kaithem/data/static/OpenFixtureLibrary/OPZFormatFixtures\.json|kaithem/src/js/thirdparty/.*