repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
        types_or:
          - "python"
          - "yaml"
          - "json"
          - "markdown"
          - "html"
    -   id: check-byte-order-marker
    -   id: check-json
    -   id: forbid-new-submodules

- repo: https://github.com/dhatim/python-license-check
  rev: 0.9.2
  hooks:
  - id: liccheck
    language: system

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.5
  hooks:
    - id: forbid-crlf
    - id: forbid-tabs

