#!/bin/sh
if [ ! -f /var/lib/kaithem/users/data/users.json ] ; then
    adduser --system --no-create-home kaithem
    #Look at this race condition here! Someone could steal that private key before we chmod it!
    openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 -keyout /var/lib/kaithem/ssl/certificate.key  -out  /var/lib/kaithem/ssl/certificate.cert -subj '/CN=localhost'
    chmod 600 /var/lib/kaithem/ssl/certificate.key
    chown kaithem /var/lib/kaithem/ssl/certificate.key
fi

usermod -a -G serial kaithem
usermod -a -G dialout kaithem
usermod -a -G audio kaithem
usermod -a -G gpio kaithem
usermod -a -G i2c kaithem
usermod -a -G video kaithem
usermod -a -G spi kaithem
usermod -a -G uucp kaithem
groupadd -r kaithem
usermod -a -G kaithem kaithem

chmod -R 700 /usr/share/kaithem/
chown -R kaithem /usr/share/kaithem/
chgrp -R kaithem /usr/share/kaithem/

mkdir /var/log/kaithem
chmod -R 700 /var/log/kaithem
chown -R kaithem /var/log/kaithem
chgrp -R kaithem /var/log/kaithem

mkdir /var/lib/kaithem
chown -R kaithem /var/lib/kaithem
chmod -R 700 /var/lib/kaithem/
chgrp -R kaithem /var/lib/kaithem/

#Don't chgrp this, that's on purpose to keep the ssl keys secret and because there's not much reason to
mkdir /var/lib/kaithem/ssl
chown -R  kaithem /var/lib/kaithem/ssl
chmod -R 700 /var/lib/kaithem/ssl

systemctl enable kaithem.service
kaithem --initialpackagesetup x
systemctl start kaithem.service
