#!/bin/bash

# This script exists to block uv publish from being called directly.

target_command="publish"

should_block=false

# Iterate through the arguments passed to the script
for arg in "$@"; do
  if [[ "$arg" == "$target_command" ]]; then
    should_block=true
  fi
done


if [ -n "$MAKEFLAGS" ]; then
echo "Running under make."
else
    if $should_block; then
        echo "Use the makefile, kaithem direnv forbids direct calls to uv publish in this dir."
        exit 1
    fi
fi


~/.local/bin/uv "$@"