services:

  kaithem-builder:
    image: kaithem-builder:${KAITHEM_VERSION:?error}
    build:
      # Expects to be in a projects directory containing
      # Kaithem alongside Dashbeard.
      context: ../../
      dockerfile: KaithemAutomation/docker/build/Dockerfile

  playwright:
    image: kaithem-dev-playwright:${KAITHEM_VERSION:?error}
    build:
      context: ../../
      dockerfile: KaithemAutomation/docker/playwright/Dockerfile
    user: "${KAITHEM_UID:?error}:${KAITHEM_GROUP:?error}"

    volumes:
      - ./../../KaithemAutomation:/work
  
    working_dir: /work
    network_mode: host



  kaithem:
    image: kaithem:${KAITHEM_VERSION:?error}
    build:
      context: ../../
      dockerfile: KaithemAutomation/docker/app/Dockerfile
      args:
        - KAITHEM_VERSION=${KAITHEM_VERSION:?error}

    privileged: true

    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99


    user: "${KAITHEM_UID:?error}:${KAITHEM_GROUP:?error}"
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PIPEWIRE_REMOTE=pipewire-0
      - USER=${KAITHEM_USER:?error}
      - LOGNAME=${KAITHEM_USER:?error}
      - DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}
      - KAITHEM_AUDIO_API=jack
      - XDG_SESSION_TYPE=${XDG_SESSION_TYPE}
      - XAUTHORITY=${XAUTHORITY}
      - PIPEWIRE_LATENCY="128/48000"
      - PIPEWIRE_QUANTUM="128/48000"

    volumes:
      # Seems to be needed for getpass.getuser()
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/lib/locale:/usr/lib/locale:ro
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - /var/run/dbus:/var/run/dbus
      - ${HOME}/kaithem-docker-home:/app-home
      - /dev:/dev
      - /tmp:/tmp

      # Use the host certificate bundle so we don't have to keep
      # updating the bundle
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro

    network_mode: host
    pid: host

    group_add:
      - audio
      - video
      - dialout

    restart: unless-stopped

  kaithem-dev:
    extends: 
      service: kaithem
    image: kaithem-dev:${KAITHEM_VERSION:?error}
    build:
      context: ../../
      dockerfile: KaithemAutomation/docker/dev/Dockerfile

    volumes:
      # Mount in the Kaithem files, so that we can do dev with it.
      - ./../../KaithemAutomation:/workspace/KaithemAutomation
      - ./../../Dashbeard:/workspace/Dashbeard
      - /workspace/KaithemAutomation/.venv
      - /workspace/KaithemAutomation/.test_venvs
      - /workspace/KaithemAutomation/__pycache__
      - /workspace/KaithemAutomation/target
      - /workspace/KaithemAutomation/dist
      - /workspace/KaithemAutomation/wasm_kegs/__pycache__
      - /workspace/Dashbeard/.npm
      - /workspace/Dashbeard/dist
      - /workspace/uv_cache

  kaithem-kiosk:
    image: kaithem-kiosk:${KAITHEM_VERSION:?error}
    build:
      context: ../../
      dockerfile: KaithemAutomation/docker/kiosk/Dockerfile
      args:
        - KAITHEM_VERSION=${KAITHEM_VERSION:?error}

    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99

    security_opt:
    - apparmor:unconfined

    user: "${KAITHEM_UID:?error}:${KAITHEM_GROUP:?error}"
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY:-wayland-0}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - PIPEWIRE_REMOTE=pipewire-0
      - USER=${KAITHEM_USER:?error}
      - HOME=/home/${KAITHEM_USER:?error}
      - LOGNAME=${KAITHEM_USER:?error}
      - DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}
      - KAITHEM_AUDIO_API=jack
      - XDG_SESSION_TYPE=${XDG_SESSION_TYPE}
      - XAUTHORITY=${XAUTHORITY}
      - PIPEWIRE_LATENCY="128/48000"
      - PIPEWIRE_QUANTUM="128/48000"
      - KIOSK_URL="${KIOSK_URL:-http://localhost:8002}"

    volumes:
      - /var/run/dbus:/var/run/dbus
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /usr/lib/locale:/usr/lib/locale:ro

    tmpfs:
      - /dev/shm:size=300M,mode=1777

    network_mode: host

    group_add:
      - audio
      - video
      - dialout

    restart: unless-stopped

  # kaithem-host-setup:
  #   image: kaithem-host-setup:dev
  #   build:
  #     context: ../../
  #     dockerfile_inline: |
  #       FROM alpine:3.14
  #       cat <<'EOF' > /setup.sh
  #       #!/bin/sh
  #       mkdir -p /home/$USER/kaithem
  #       mkdir -p /home/$USER/.cache
  #       mkdir -p /home/$USER/.local/kaithem
  #       EOF
  #       ENTRYPOINT ["/setup.sh"]


  #   user: "${KAITHEM_UID}:${KAITHEM_GROUP}"

  #   volumes:
  #     - /home/$KAITHEM_USER:/home/$KAITHEM_USER

