genericFixtureClasses = {
    "7ch DGBR": [
        ["dim", "intensity"],
        ["green", "green"],
        ["blue", "blue"],
        ["red", "red"],
        ["unused1", "unused"],
        ["unused2", "unused"],
        ["unused3", "unused"],
        ["unused4", "unused"],
    ],
    "7ch DBGR": [
        ["dim", "intensity"],
        ["blue", "blue"],
        ["green", "green"],
        ["red", "red"],
        ["unused1", "unused"],
        ["unused2", "unused"],
        ["unused3", "unused"],
        ["unused4", "unused"],
    ],
    "7ch DRGB": [
        ["dim", "intensity"],
        ["red", "red"],
        ["green", "green"],
        ["blue", "blue"],
        ["unused1", "unused"],
        ["unused2", "unused"],
        ["unused3", "unused"],
        ["unused4", "unused"],
    ],
    "3ch RGB": [["red", "red"], ["green", "green"], ["blue", "blue"]],
}
