name: kaithem
summary: An automation server allowing web-based control of hardware devices
description: |
    Kaithem is a python-based automation server especially focused on interactive art
    and theater.
version: test
base: core22
confinement: devmode

parts:
  kaithem:
    plugin: python
    source: .
    stage-packages:
      - mpv
      - python3
      - lm-sensors
      - python3-gi
      - python3-gst-1.0
      - python3-libnacl
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - swh-plugins
      - tap-plugins
      - caps
      - gstreamer1.0-plugins-ugly
      - fluidsynth
      - libfluidsynth3
      - gstreamer1.0-pocketsphinx
      - x42-plugins
      - baresip
      - autotalent
      - rtl-433
      - gstreamer1.0-opencv
      - gstreamer1.0-vaapi
      - pipewire-audio-client-libraries
      
      # Utils not directly needed by kaithem but we want to make sure they're always in
      # The web terminal
      - vim-tiny
      - units 
      - git 
      - wget
      - gstreamer1.0-tools
      - neofetch


apps:
  kaithem:
    command: /usr/bin/pw-jack python3 -m kaithem
    plugs:
      - raw-usb
      - hardware-observe
      - alsa
      - jack1
      - time-control
      - timezone-control
      - vcio
      - wayland
      - serial-port
      - network-manager-observe
      - network
      - network-bind
      - camera
      - audio-playback
      - audio-record
      - gpio
      - gpio-control
      - log-observe
      - media-control
      - system-observe
      - upower-observe
      - shared-memory
      - pulseaudio
      - x11
      - spi
      - optical-drive
      - opengl
      - joystick
      - i2c
      - io-ports-control
      - display-control
      - dvb
      - cups-control
      - avahi-observe

plugs:
  shared-memory:
    private: true