name: kaithem
summary: An automation server allowing web-based control of hardware devices
description: |
    Kaithem is a python-based automation server especially focused on interactive art
    and theater.
version: test
base: core22
confinement: strict

parts:
  kaithem:
    plugin: python
    source: .
    python-packages:
      - tflite-runtime
      - aioesphomeapi
      # These are normally included with kaithem but we don't do that when doing snaps
      
      - tornado
      - cherrypy
      - flask
      - mako
      - python-mpv
      - pynput
      - cheroot
      - autoslot
      - colorzero
      - ntplib
      - ntpserver
      - onvif
      - peewee
      - passlib
      - pint
      - tatsu
      - textdistance
      - tinytag
      - toml
      - typeguard
      - zeroconf
      
    stage-snaps:
      - mpv
    
    stage-packages:
      - python3
      - cython3
      - build-essential
      - python3-msgpack
      - python3-future
      - python3-serial
      - python3-tz
      - python3-dateutil
      - lm-sensors
      - python3-netifaces
      - python3-jack-client
      - python3-gst-1.0
      - python3-libnacl
      - jackd2
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - swh-plugins
      - tap-plugins
      - caps
      - gstreamer1.0-plugins-ugly
      - python3-psutil
      - fluidsynth
      - libfluidsynth3
      - network-manager
      - python3-paho-mqtt
      - python3-dbus
      - python3-lxml
      - gstreamer1.0-pocketsphinx
      - x42-plugins
      - baresip
      - autotalent
      - libmpv-dev
      - libcap2-bin
      - rtl-433
      - python3-toml
      - python3-rtmidi
      - gstreamer1.0-opencv
      - gstreamer1.0-vaapi
      - python3-pillow
      - python3-scipy
      - ffmpeg
      - python3-skimage
      - python3-setproctitle
      - python3-tornado
      - pipewire-audio-client-libraries
      - python3-opencv

apps:
  kaithem:
    command: /usr/bin/pw-jack python3 -m kaithem
    plugs:
      - raw-usb
      - hardware-observe
      - alsa
      - jack1
      - time-control
      - timezone-control
      - vcio
      - wayland
      - serial-port
      - network-manager-observe
      - network
      - network-bind
      - camera
      - audio-playback
      - audio-record
      - gpio
      - gpio-control
      - log-observe
      - media-control
      - system-observe
      - upower-observe
      - shared-memory
      - pulseaudio
      - x11
      - spi
      - optical-drive
      - opengl
      - joystick
      - i2c
      - io-ports-control
      - display-control
      - dvb
      - cups-control
      - avahi-observe

plugs:
  shared-memory:
    private: true